[2022-09-08T17:53:56.623+0500] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: expectation_dag.expectation4 manual__2022-09-08T12:53:42.560088+00:00 [queued]>
[2022-09-08T17:53:56.628+0500] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: expectation_dag.expectation4 manual__2022-09-08T12:53:42.560088+00:00 [queued]>
[2022-09-08T17:53:56.628+0500] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T17:53:56.628+0500] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-09-08T17:53:56.628+0500] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T17:53:56.642+0500] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): expectation4> on 2022-09-08 12:53:42.560088+00:00
[2022-09-08T17:53:56.646+0500] {standard_task_runner.py:52} INFO - Started process 1055155 to run task
[2022-09-08T17:53:56.648+0500] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'expectation_dag', 'expectation4', 'manual__2022-09-08T12:53:42.560088+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/expectation_dag.py', '--cfg-path', '/tmp/tmpo5opup56', '--error-file', '/tmp/tmpl14fez5s']
[2022-09-08T17:53:56.648+0500] {standard_task_runner.py:80} INFO - Job 13: Subtask expectation4
[2022-09-08T17:53:56.682+0500] {task_command.py:371} INFO - Running <TaskInstance: expectation_dag.expectation4 manual__2022-09-08T12:53:42.560088+00:00 [running]> on host shahroze
[2022-09-08T17:53:56.731+0500] {taskinstance.py:1581} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=expectation_dag
AIRFLOW_CTX_TASK_ID=expectation4
AIRFLOW_CTX_EXECUTION_DATE=2022-09-08T12:53:42.560088+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-08T12:53:42.560088+00:00
[2022-09-08T17:53:56.734+0500] {logging_mixin.py:115} INFO - {
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  },
  "meta": {},
  "result": {},
  "expectation_config": {
    "expectation_type": "expect_column_to_exist",
    "meta": {},
    "kwargs": {
      "column": "trip_distance",
      "result_format": "BASIC"
    }
  },
  "success": true
}
[2022-09-08T17:53:56.734+0500] {python.py:173} INFO - Done. Returned value was: None
[2022-09-08T17:53:56.741+0500] {taskinstance.py:1407} INFO - Marking task as SUCCESS. dag_id=expectation_dag, task_id=expectation4, execution_date=20220908T125342, start_date=20220908T125356, end_date=20220908T125356
[2022-09-08T17:53:56.780+0500] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-08T17:53:56.797+0500] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
