[2022-09-08T18:49:48.374+0500] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: expectation_dag.expect_values_in_set manual__2022-09-08T13:49:44.052113+00:00 [queued]>
[2022-09-08T18:49:48.378+0500] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: expectation_dag.expect_values_in_set manual__2022-09-08T13:49:44.052113+00:00 [queued]>
[2022-09-08T18:49:48.378+0500] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T18:49:48.378+0500] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-09-08T18:49:48.378+0500] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T18:49:48.392+0500] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): expect_values_in_set> on 2022-09-08 13:49:44.052113+00:00
[2022-09-08T18:49:48.396+0500] {standard_task_runner.py:52} INFO - Started process 1069802 to run task
[2022-09-08T18:49:48.398+0500] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'expectation_dag', 'expect_values_in_set', 'manual__2022-09-08T13:49:44.052113+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/expectation_dag.py', '--cfg-path', '/tmp/tmpg0gjhlea', '--error-file', '/tmp/tmpi7suy3mb']
[2022-09-08T18:49:48.399+0500] {standard_task_runner.py:80} INFO - Job 32: Subtask expect_values_in_set
[2022-09-08T18:49:48.449+0500] {task_command.py:371} INFO - Running <TaskInstance: expectation_dag.expect_values_in_set manual__2022-09-08T13:49:44.052113+00:00 [running]> on host shahroze
[2022-09-08T18:49:48.519+0500] {taskinstance.py:1581} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=expectation_dag
AIRFLOW_CTX_TASK_ID=expect_values_in_set
AIRFLOW_CTX_EXECUTION_DATE=2022-09-08T13:49:44.052113+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-08T13:49:44.052113+00:00
[2022-09-08T18:49:48.523+0500] {python.py:173} INFO - Done. Returned value was: False
[2022-09-08T18:49:48.540+0500] {taskinstance.py:1407} INFO - Marking task as SUCCESS. dag_id=expectation_dag, task_id=expect_values_in_set, execution_date=20220908T134944, start_date=20220908T134948, end_date=20220908T134948
[2022-09-08T18:49:48.570+0500] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-08T18:49:48.594+0500] {local_task_job.py:279} INFO - 4 downstream tasks scheduled from follow-on schedule check
